### ISSUE TITLE
Add option to select a popout background

### ISSUE THREAD

**Issue by FFY00** [puckzxz/NotAnotherAnimeTheme#107]
Right now when we click on something (ex. an user), we get presented with the following.

![bd-theme-user-popout](https://user-images.githubusercontent.com/11718923/54455457-bf5e5980-4753-11e9-8b66-e9845470abe4.png)

Would it be possible to add an option for a background there?

Preview:

![bd-theme-user-popout-bg](https://user-images.githubusercontent.com/11718923/54455576-182df200-4754-11e9-95d2-45d034bf554a.png)

Getting an option to configure the "Message @..." would also be great!

Thanks :)

**Comment by puckzxz** [comment]
Thanks for the suggestion. Quake and I will definitely look into adding more customization options

**Comment by FFY00** [comment]
Well, this seems to be working for users. I don't really have the time to work on the other popouts.

```css
.userPopout-3XzG_A {
    background: url(https://i.imgur.com/kvPnkJY.jpg) center/cover no-repeat;
}

.userPopout-3XzG_A .role-2irmRk,
.userPopout-3XzG_A .header-2BwW8b,
.userPopout-3XzG_A .body-3iLsc4,
.userPopout-3XzG_A .footer-1fjuF6,
.userPopout-3XzG_A .quickMessage-1yeL4E,
.userPopout-3XzG_A .note-3kmerW textarea:focus {
    background: rgba(0, 0, 0, 0) !important;
}
```

**Comment by FFY00** [comment]
Here's my final theme. Perhaps you could integrate some of the changes to the main theme :grin:.

https://gist.github.com/FFY00/0dd43b3ee2fac5504c498f8850a205c4

**Comment by Qu4k3** [comment]
We made some changes in order to achieve something like this and corrected some colors.

Refer to: #109

![image](https://user-images.githubusercontent.com/9118664/54494407-24dc5280-48da-11e9-9a07-82aeb0342d4b.png)

In order to change the background like in the image (or moreless):
```css
.userPopout-3XzG_A {
    background: linear-gradient(175deg, #1B1220, #B8424A, #17335e);
} 
```
Or as you mentioned, with an image:
```css
.userPopout-3XzG_A {
    background: url(https://i.imgur.com/kvPnkJY.jpg) center/cover no-repeat;
}
```

Feel free to reopen this issue or letting us know in #suggestions / #issues-bugs inside our Discord server for further changes.
