### ISSUE TITLE
User popout background images are no longer working

### ISSUE THREAD

**Issue by quincynyan** [puckzxz/NotAnotherAnimeTheme#221]
I've set 
```css
--small-user-popout-background-image: url('https://i.imgur.com/v1ODdsv.gif');
--small-user-popout-background-transparency: #00000099;
--small-user-popout-background-image-position: center;
--big-user-popout-background-image: url('https://i.imgur.com/BXr6I0G.gif');
--big-user-popout-background-transparency: #00000099;
--big-user-popout-background-image-position: center;
```
in `:root` but they're not showing up in discord. 

It looks like the theme uses `.userPopout-2j1gM4` and `.root-8LYsGj` which are not in the latest Discord version anymore.

**Comment by WubzyGD** [comment]
to my knowledge, the popouts are deprecated for the theme because of discord's user theming. the popout bg feature was around long before you could set your own themes and banners and such. i don't know what puck intends to do moving forward but i think he's just leaving it.

```css
div .userPopoutOuter_d67f56 .userProfileInnerThemedNonPremium_b64fb4 {
  background-image: var(--small-user-popout-background-image);
  background-position: var(--small-user-popout-background-image-position);
  background-size: cover;
}

div .userPopoutOuter_d67f56 .userProfileInnerThemedNonPremium_b64fb4 .userPopoutOverlayBackground__3e7e6 {
  background: var(--small-user-popout-background-transparency);
}

div .userProfileModalOuter__90b4a .userProfileInnerThemedNonPremium_b64fb4 {
  background-image: var(--big-user-popout-background-image);
  background-position: var(--big-user-popout-background-image-position);
  background-size: cover;
}

div .userProfileModalOuter__90b4a .userProfileInnerThemedNonPremium_b64fb4 .userProfileModalOverlayBackground_a5b043 {
 background: var(--big-user-popout-background-transparency);
}
```

add that to the bottom of your CSS file. it will add popout backgrounds ONLY to popouts of users without theming. doing the themed ones requires a fair bit of headway that i'm not feeling geared up to go through.

**Comment by quincynyan** [comment]
Sorry I'm a week late OwO. It looks like the latest update changed the class names and the code you provided is not working

**Comment by puckzxz** [comment]
> Sorry I'm a week late OwO. It looks like the latest update changed the class names and the code you provided is not working.
> 
> But yes, I just want to theme non-nitro users, because the grey color is really out of place with my pink background. (Separate issue: when replying somebody, the reply tab, and also the "jump to present message" tab are still grey and unstyled)

Try this
```css
div .userPopoutOuter_c69a7b .userProfileInnerThemedNonPremium_c69a7b {
  background-image: var(--small-user-popout-background-image);
  background-position: var(--small-user-popout-background-image-position);
  background-size: cover;
}

div .userPopoutOuter_c69a7b .userProfileInnerThemedNonPremium_c69a7b .userPopoutOverlayBackground_c69a7b {
  background: var(--small-user-popout-background-transparency);
}

div .userProfileModalOuter_c69a7b .userProfileInnerThemedNonPremium_c69a7b {
  background-image: var(--big-user-popout-background-image);
  background-position: var(--big-user-popout-background-image-position);
  background-size: cover;
}

div .userProfileModalOuter_c69a7b .userProfileInnerThemedNonPremium_c69a7b .userProfileModalOverlayBackground_c69a7b {
 background: var(--big-user-popout-background-transparency);
}
```

**Comment by quincynyan** [comment]
Nope, not working. It looks like they removed the `NonPremium` class, so that all the classes are the same now, whether themed or not?

**Comment by WubzyGD** [comment]
I will update them at some point in the next few hours

**Comment by quincynyan** [comment]
Noticed this in the class names, might help:
![image](https://github.com/puckzxz/NotAnotherAnimeTheme/assets/65074780/8a2186f5-38c9-4ff8-ac15-2e567fcbf5a8)

**Comment by quincynyan** [comment]
This fixed it

```css
div .userProfileOuterUnthemed_c69a7b .userPopoutInner_c69a7b {
  background-image: var(--small-user-popout-background-image);
  background-position: var(--small-user-popout-background-image-position);
  background-size: cover;
}

div .userProfileOuterUnthemed_c69a7b .userPopoutInner_c69a7b .body_b07019 {
  background: var(--small-user-popout-background-transparency);
}

div .userProfileOuterUnthemed_c69a7b .userProfileModalInner_c69a7b {
  background-image: var(--big-user-popout-background-image);
  background-position: var(--big-user-popout-background-image-position);
  background-size: cover;
}

div .userProfileOuterUnthemed_c69a7b .userProfileModalInner_c69a7b .fullSizeOverlayBackground_c69a7b {
 background: var(--big-user-popout-background-transparency);
}
```

Is puck interested in allowing this in a PR?
