### ISSUE TITLE
I found a new issue as of after the update

### ISSUE THREAD

**Issue by pkpkpkpkpkpkpkpkthisusernmamewasnotavil** [puckzxz/NotAnotherAnimeTheme#229]
I really like this theme and have been using a modified version of it for quite some time.
But I noticed after today's update some transparency on lots of frosted glass themes is "broken".
This window lacks a back texture it would be nice if you could fix this (As I don't understand BD's theme format for discord.) Thank you.
![Image](https://github.com/user-attachments/assets/706c3b6f-1c17-4265-94f2-c65b9f7a18e0)

**Comment by dezgasting** [comment]
for me the theme doesn't even work after the update lol

**Comment by puckzxz** [comment]
This should be solved in https://github.com/puckzxz/NotAnotherAnimeTheme/commit/b5d6019f2ba64085c4ce692912062f829eae7215

If you want to customize further, you can just this code to have whatever background color you want

```css
.floating__01ae2 {
  background-color: color-mix(
    in srgb,
    var(--theme-transparency),
    transparent 20%
  );
}
```
